In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('tinden-jan-2017.csv', sep=";")

In [3]:
df.describe()

Dag      TA-01      TA-07      TA-13      TA-19        TAM  \
count  31.000000  31.000000  31.000000  31.000000  31.000000  31.000000   
mean   16.000000  -4.883871  -4.909677  -4.264516  -4.977419  -4.761290   
std     9.092121   4.854832   4.353570   4.754054   4.638442   4.290119   
min     1.000000 -15.100000 -14.500000 -13.400000 -13.400000 -13.100000   
25%     8.500000  -7.850000  -7.500000  -7.500000  -8.300000  -7.300000   
50%    16.000000  -5.200000  -5.200000  -4.300000  -4.900000  -4.800000   
75%    23.500000  -1.000000  -1.550000  -0.150000  -1.200000  -1.200000   
max    31.000000   5.000000   2.200000   2.900000   2.800000   1.600000   

             TAX        TAN  
count  31.000000  31.000000  
mean   -2.193548  -7.464516  
std     4.427711   4.371159  
min   -11.300000 -15.400000  
25%    -4.950000 -10.600000  
50%    -1.600000  -7.600000  
75%     1.650000  -4.150000  
max     5.900000  -0.100000

In [4]:
x_data = df.drop(['TA-13'],axis=1)

In [5]:
y_val = df['TA-13']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(x_data,y_val,test_size=0.3,random_state=101)

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
scaler = MinMaxScaler()

In [10]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [11]:
X_train = pd.DataFrame(data=scaler.transform(X_train),columns = X_train.columns,index=X_train.index)

In [12]:
X_test = pd.DataFrame(data=scaler.transform(X_test),columns = X_test.columns,index=X_test.index)

In [13]:
df.columns

Index(['Dag', 'TA-01', 'TA-07', 'TA-13', 'TA-19', 'TAM', 'TAX', 'TAN'], dtype='object')

In [14]:
import tensorflow as tf

In [15]:
dag = tf.feature_column.numeric_column('Dag')

In [16]:
TA1 = tf.feature_column.numeric_column('TA-01')

In [17]:
TA7 =  tf.feature_column.numeric_column('TA-07')

In [18]:
TA13 =  tf.feature_column.numeric_column('TA-13')

In [19]:
TA19 =  tf.feature_column.numeric_column('TA-19')

In [20]:
TAM =  tf.feature_column.numeric_column('TAM')

In [21]:
TAX =  tf.feature_column.numeric_column('TAX')

In [22]:
TAN =  tf.feature_column.numeric_column('TAN')

In [23]:
feat_cols = [dag,TA1,TA7,TA19,TAM,TAX,TAN]

In [24]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,batch_size=5,num_epochs=10000,shuffle=True)

In [25]:
model = tf.estimator.DNNRegressor(hidden_units=[9,9,9],feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_keep_checkpoint_max': 5, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_tf_random_seed': 1, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/var/folders/fx/lb1_syp12qgfwfyn206tc831vpdc5b/T/tmp0abmnyr3', '_save_summary_steps': 100, '_log_step_count_steps': 100, '_session_config': None}


In [26]:
model.train(input_fn=input_func,steps=25000)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/fx/lb1_syp12qgfwfyn206tc831vpdc5b/T/tmp0abmnyr3/model.ckpt.
INFO:tensorflow:step = 1, loss = 194.268
INFO:tensorflow:global_step/sec: 625.998
INFO:tensorflow:step = 101, loss = 3.2408 (0.161 sec)
INFO:tensorflow:global_step/sec: 658.314
INFO:tensorflow:step = 201, loss = 4.16248 (0.152 sec)
INFO:tensorflow:global_step/sec: 656.836
INFO:tensorflow:step = 301, loss = 0.316583 (0.152 sec)
INFO:tensorflow:global_step/sec: 668.347
INFO:tensorflow:step = 401, loss = 1.32433 (0.150 sec)
INFO:tensorflow:global_step/sec: 651.712
INFO:tensorflow:step = 501, loss = 1.84932 (0.153 sec)
INFO:tensorflow:global_step/sec: 665.269
INFO:tensorflow:step = 601, loss = 1.18718 (0.150 sec)
INFO:tensorflow:global_step/sec: 668.999
INFO:tensorflow:step = 701, loss = 1.32076 (0.150 sec)
INFO:tensorflow:global_step/sec: 658.367
INFO:tensorflow:step = 801, loss = 0.75385 (0.152 sec)
INFO:tensorflow:global_step/

INFO:tensorflow:global_step/sec: 630.375
INFO:tensorflow:step = 8301, loss = 0.0767398 (0.159 sec)
INFO:tensorflow:global_step/sec: 487.86
INFO:tensorflow:step = 8401, loss = 0.157668 (0.205 sec)
INFO:tensorflow:global_step/sec: 583.485
INFO:tensorflow:step = 8501, loss = 0.0330647 (0.171 sec)
INFO:tensorflow:global_step/sec: 597.983
INFO:tensorflow:step = 8601, loss = 0.111911 (0.167 sec)
INFO:tensorflow:global_step/sec: 649.683
INFO:tensorflow:step = 8701, loss = 0.211233 (0.154 sec)
INFO:tensorflow:global_step/sec: 616.857
INFO:tensorflow:step = 8801, loss = 0.258944 (0.164 sec)
INFO:tensorflow:global_step/sec: 392.217
INFO:tensorflow:step = 8901, loss = 0.311184 (0.254 sec)
INFO:tensorflow:global_step/sec: 600.122
INFO:tensorflow:step = 9001, loss = 0.200589 (0.167 sec)
INFO:tensorflow:global_step/sec: 423.164
INFO:tensorflow:step = 9101, loss = 0.0879953 (0.237 sec)
INFO:tensorflow:global_step/sec: 516.919
INFO:tensorflow:step = 9201, loss = 0.103135 (0.192 sec)
INFO:tensorflow:gl

INFO:tensorflow:global_step/sec: 494.751
INFO:tensorflow:step = 16601, loss = 0.140986 (0.202 sec)
INFO:tensorflow:global_step/sec: 551.761
INFO:tensorflow:step = 16701, loss = 0.0572125 (0.181 sec)
INFO:tensorflow:global_step/sec: 667.031
INFO:tensorflow:step = 16801, loss = 0.0954527 (0.150 sec)
INFO:tensorflow:global_step/sec: 674.295
INFO:tensorflow:step = 16901, loss = 0.0208714 (0.148 sec)
INFO:tensorflow:global_step/sec: 666.388
INFO:tensorflow:step = 17001, loss = 0.00970433 (0.150 sec)
INFO:tensorflow:global_step/sec: 640.122
INFO:tensorflow:step = 17101, loss = 0.0264673 (0.156 sec)
INFO:tensorflow:global_step/sec: 662.024
INFO:tensorflow:step = 17201, loss = 0.0241985 (0.151 sec)
INFO:tensorflow:global_step/sec: 666.992
INFO:tensorflow:step = 17301, loss = 0.0502737 (0.150 sec)
INFO:tensorflow:global_step/sec: 660.502
INFO:tensorflow:step = 17401, loss = 0.0766604 (0.151 sec)
INFO:tensorflow:global_step/sec: 663.962
INFO:tensorflow:step = 17501, loss = 0.084964 (0.151 sec)
I

INFO:tensorflow:step = 24801, loss = 0.0267323 (0.152 sec)
INFO:tensorflow:global_step/sec: 654.274
INFO:tensorflow:step = 24901, loss = 0.0747552 (0.153 sec)
INFO:tensorflow:Saving checkpoints for 25000 into /var/folders/fx/lb1_syp12qgfwfyn206tc831vpdc5b/T/tmp0abmnyr3/model.ckpt.
INFO:tensorflow:Loss for final step: 0.0204945.


In [27]:
predict_input_func = tf.estimator.inputs.pandas_input_fn(
      x=X_test,
      batch_size=10,
      num_epochs=1,
      shuffle=False)

In [28]:
pred_gen = model.predict(predict_input_func)

In [47]:
predictions = list(pred_gen)

INFO:tensorflow:Restoring parameters from /var/folders/fx/lb1_syp12qgfwfyn206tc831vpdc5b/T/tmp8av5seaf/model.ckpt-25000


In [48]:
final_preds = []
for pred in predictions:
    final_preds.append(pred['predictions'])

In [49]:
from sklearn.metrics import mean_squared_error

In [50]:
mean_squared_error(y_test,final_preds)**0.5

1.0846876392467406

In [53]:
mean_squared_error

<function sklearn.metrics.regression.mean_squared_error>

In [55]:
final_preds

[array([-0.85113448], dtype=float32),
 array([-4.83678532], dtype=float32),
 array([-6.79656744], dtype=float32),
 array([ 2.22030091], dtype=float32),
 array([ 1.40666676], dtype=float32),
 array([-2.06359196], dtype=float32),
 array([-5.95039797], dtype=float32),
 array([ 0.38307381], dtype=float32),
 array([ 2.28649378], dtype=float32),
 array([-0.4433881], dtype=float32)]